#
# appveyor.yml
#
#

version: 0.0.1.{build}

branches:
  only:
    - master

image: Visual Studio 2015

before_build:
  - choco install opencover.portable
  - choco install codecov

build:
  - project: Api.sln
  - verbosity: minimal

test_script:
  - OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\Api.Tests\bin\Debug\Api.Tests.dll -noshadow" -output:".\coverage.xml"
  - codecov -f "coverage.xml"

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/4a976a2287ab49087f35
    method: POST
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
