#
# appveyor.yml
#
#

version: 0.0.1.{build}

branches:
  only:
    - master

image: Visual Studio 2015

build_script:
  - cmd: dotnet restore
  - cmd: dotnet build

test_script:
  - cmd: dotnet test Api.Tests 

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/4a976a2287ab49087f35
    method: POST
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
